apiVersion: apps/v1
kind: Deployment
metadata:
  name: apollo-admin
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: apollo-admin
  template:
    metadata:
      labels:
        app: apollo-admin
    spec:
      containers:
      - image: 192.168.2.117:5000/center-platform/apollo/adminservice:latest
        imagePullPolicy: Always
        name: apollo-admin
        ports:
        - containerPort: 8090