apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-center
  namespace: center-platform
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: content-center
  template:
    metadata:
      labels:
        app: content-center
    spec:
      containers:
      - image: 192.168.2.117:5000/center-platform/content-center:dev
        imagePullPolicy: Always
        name: content-center
        ports:
        - containerPort: 8080
        env:
          - name: "ENV"
            value: "dev"
          - name: "APOLLO_META_URL"
            value: "http://apoconf-dev.jmtop.com"