apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - image: 192.168.2.117:5000/springcloud/eureka
        name: eureka
        ports:
        - containerPort: 8761