apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: base-app
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - image: registry-vpc.cn-hongkong.aliyuncs.com/center-platform/eureka-server:qa
        imagePullPolicy: Always
        name: eureka-server
        ports:
        - containerPort: 8080
        env:
          - name: "ENV"
            value: "FAT"
          - name: "APOLLO_META_URL"
            value: "http://apoconf-qa.jmtop.com"
      imagePullSecrets:
      - name: ali-docker-registry