apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
      - image: openzipkin/zipkin
        imagePullPolicy: Always
        name: zipkin
        ports:
        - containerPort: 9411
        env:
          - name: "STORAGE_TYPE"
            value: "mysql"
          - name: "MYSQL_HOST"
            value: "192.168.2.114"
          - name: "MYSQL_TCP_PORT"
            value: "30006"
          - name: "MYSQL_DB"
            value: "zipkin"
          - name: "MYSQL_USER"
            value: "root"
          - name: "MYSQL_PASS"
            value: "zhongtai123"
