apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management-svc
spec:
  ports:
  - name: rabbitmq-management-svc
    nodePort: 31672
    port: 15672
    targetPort: 15672
    protocol: TCP
  selector:
    app: rabbitmq
  type: NodePort