apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
spec:
  ports:
  - name: rabbitmq-svc
    nodePort: 30672
    port: 5672
    targetPort: 5672
    protocol: TCP
  selector:
    app: rabbitmq
  type: NodePort