apiVersion: v1
kind: Service
metadata:
  name: apollo-admin-svc
spec:
  ports:
  - name: apollo-admin-svc
    nodePort: 30100
    port: 8090
    targetPort: 8090
    protocol: TCP
  selector:
    app: apollo-admin
  type: NodePort