apiVersion: v1
kind: Service
metadata:
  name: apollo-portal-svc
spec:
  ports:
  - name: apollo-portal-svc
    nodePort: 30102
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: apollo-portal
  type: NodePort