apiVersion: v1
kind: Service
metadata:
  name: apollo-mysql-svc
spec:
  ports:
  - name: apollo-mysql-svc
    nodePort: 30007
    port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: apollo-mysql
  type: NodePort