apiVersion: v1
kind: Service
metadata:
  name: apollo-config-svc
spec:
  ports:
  - name: apollo-config-svc
    nodePort: 30101
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: apollo-config
  type: NodePort