apiVersion: v1
kind: Service
metadata:
  name: market-bonus-svc
  namespace: bonus-platform
spec:
  ports:
  - name: market-bonus-svc
    nodePort: 30206
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: market-bonus
  type: NodePort