apiVersion: v1
kind: Service
metadata:
  name: bonus-bonus-svc
  namespace: center-platform
spec:
  ports:
  - name: bonus-bonus-svc
    nodePort: 30206
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: bonus-bonus
  type: NodePort