apiVersion: v1
kind: Service
metadata:
  name: eureka-server-svc
spec:
  ports:
  - name: eureka-server-svc
    nodePort: 30106
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: eureka-server
  type: NodePort