apiVersion: v1
kind: Service
metadata:
  name: eureka-svc
spec:
  ports:
  - name: eureka-svc
    nodePort: 30002
    port: 8761
    targetPort: 8761
    protocol: TCP
  selector:
    app: eureka
  type: NodePort