apiVersion: v1
kind: Service
metadata:
  name: gateway-server-svc
spec:
  ports:
  - name: gateway-server-svc
    nodePort: 30108
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: gateway-server
  type: NodePort