apiVersion: v1
kind: Service
metadata:
  name: product-center-svc
  namespace: center-platform
spec:
  ports:
  - name: product-center-svc
    nodePort: 30205
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: product-center
  type: NodePort