apiVersion: v1
kind: Service
metadata:
  name: schedule-admin-svc
spec:
  ports:
  - name: schedule-admin-svc
    nodePort: 30104
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: schedule-admin
  type: NodePort