apiVersion: v1
kind: Service
metadata:
  name: trade-center-svc
  namespace: center-platform
spec:
  ports:
  - name: trade-center-svc
    nodePort: 30203
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: trade-center
  type: NodePort