apiVersion: v1
kind: Service
metadata:
  name: user-center-svc
  namespace: center-platform
spec:
  ports:
  - name: user-center-svc
    nodePort: 30202
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: user-center
  type: NodePort