apiVersion: v1
kind: Service
metadata:
  name: zhongtai-pg-svc
spec:
  ports:
  - name: zhongtai-pg-svc
    nodePort: 30432
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: zhongtai-pg
  type: NodePort