apiVersion: v1
kind: Service
metadata:
  name: zipkin-server-svc
spec:
  ports:
  - name: zipkin-server-svc
    nodePort: 30107
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: zipkin-server
  type: NodePort