apiVersion: v1
kind: Service
metadata:
  name: zipkin-svc
spec:
  ports:
  - name: zipkin-svc
    nodePort: 30105
    port: 9411
    targetPort: 9411
    protocol: TCP
  selector:
    app: zipkin
  type: NodePort