apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apollo-logs-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs
