apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-center-platform-pvc
  namespace: center-platform
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs
  selector:
    matchLabels:
      