apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-conf-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
  selector:
    matchLabels:
      app: redis