apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: apollo-config-ingress
  namespace: default
  annotations:
    proxy_connect_timeout: "10s"
    proxy_send_timeout: "999s"
    proxy_read_timeout: "999s"
spec:
  rules:
  - host: apoconf-dev.jmtop.com
    http:
      paths:
      - backend:
          serviceName: apollo-config-svc
          servicePort: 8080
        path: /