apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: apollo-config-ingress
  namespace: default
  annotations:
    nginx.org/proxy-connect-timeout: "10s"
    nginx.org/proxy-send-timeout: "999s"
    nginx.org/proxy-read-timeout: "999s"
spec:
  rules:
  - host: apoconf-dev.jmtop.com
    http:
      paths:
      - backend:
          serviceName: apollo-config-svc
          servicePort: 8081
        path: /