FROM java:8

MAINTAINER Regend

COPY build/libs/*.jar /usr/local/lib/

ENV TZ=Asia/Shanghai

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENTRYPOINT nohup java -Denv=$ENV -jar -Dserver.port=8080 -Dlogging.file=/usr/local/lib/app.log /usr/local/lib/*.jar --apollo.meta=$APOLLO_META_URL 2>&1