FROM java:8

MAINTAINER Regend

COPY *facade/*provider/ /usr/local/lib/

ENV TZ=Asia/Shanghai

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENTRYPOINT nohup java -jar -Xms512m -Xmx1024m -XX:MaxPermSize=512m -Dserver.port=8080 /usr/local/lib/*.jar > /opt/logs/app.log 2>&1