FROM java:8

MAINTAINER Regend

COPY *facade/*provider/build/libs/*.jar /usr/local/lib/

ENV TZ=Asia/Shanghai

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENTRYPOINT nohup java -jar -Denv=$ENV -Xms512m -Xmx1024m -XX:MaxPermSize=512m -Dserver.port=8080 -Dlogging.file=/usr/local/lib/app.log /usr/local/lib/*.jar --apollo.meta=$APOLLO_META_URL 2>&1