FROM java:8

MAINTAINER Regend

COPY apollo-configservice /home/apollo-configservice

ENV TZ=Asia/Shanghai

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENTRYPOINT ./home/apollo-configservice/scripts/startup.sh && tail -200f /opt/logs/*/*.log