FROM java:8

MAINTAINER Regend

COPY apollo-adminservice /home/apollo-adminservice

ENV TZ=Asia/Shanghai

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENTRYPOINT ./home/apollo-adminservice/scripts/startup.sh