FROM java:8

MAINTAINER Regend

COPY apollo-portal /home/apollo-portal

ENV TZ=Asia/Shanghai

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENTRYPOINT ./home/apollo-portal/scripts/startup.sh && tail -200f /home/apollo-portal/scripts/startup.sh