FROM tomcat:9.0-jre8

MAINTAINER Regend

COPY ./*.war /usr/local/tomcat/webapps/

ENV TZ=Asia/Shanghai

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENTRYPOINT /usr/local/tomcat/bin/startup.sh && tail -200f /usr/local/tomcat/logs/catalina.out

EXPOSE 8080