apiVersion: v1
kind: PersistentVolume
metadata:
  name: apollo-logs-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /home/logs/apollo
    server: 192.168.2.118