apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-conf-pv
  labels:
    app: redis
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /home/k8s/conf/redis-6379.conf
    server: 192.168.2.118