apiVersion: v1
kind: PersistentVolume
metadata:
  name: schedule-logs-pv
  labels:
    app: schedule
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /home/logs/schedule
    server: 192.168.2.118