apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pg
    spec:
      containers:
      - image: postgres:9.4
        name: pg
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: zhongtai-pg-volume
          mountPath: /var/lib/postgresql/data
        env:
        - name: POSTGRES_PASSWORD
          value: 'zhongtai123'
      volumes: 
      - name: zhongtai-pg-volume
        hostPath:
          path: /data/pg
      nodeSelector:
        mysql: mysql-apollo