apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: base
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - image: rabbitmq:3-management
        imagePullPolicy: Always
        name: rabbitmq
        ports:
        - containerPort: 15672
        - containerPort: 5672