apiVersion: v1
kind: ReplicationController
metadata:
  name: apollo-admin
spec:
  replicas: 1
  selector:
    app: apollo-admin
  template:
    metadata:
      labels:
        app: apollo-admin
    spec:
      containers:
      - image: 192.168.2.117:5000/center-platform/apollo/adminserver
        name: apollo-admin
        ports:
        - containerPort: 8090