apiVersion: v1
kind: ReplicationController
metadata:
  name: apollo-config
spec:
  replicas: 1
  selector:
    app: apollo-config
  template:
    metadata:
      labels:
        app: apollo-config
    spec:
      containers:
      - image: 192.168.2.117:5000/center-platform/apollo/configserver
        name: apollo-config
        ports:
        - containerPort: 8090