apiVersion: v1
kind: ReplicationController
metadata:
  name: zhongtai-pg
spec:
  replicas: 1
  selector:
    app: zhongtai-pg
  template:
    metadata:
      labels:
        app: zhongtai-pg
    spec:
      containers:
      - image: postgres:9.4
        name: zhongtai-pg
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: zhongtai-pg-volume
          mountPath: /var/lib/postgresql/data
        env:
        - name: POSTGRES_PASSWORD
          value: 'zhongtai123'
      volumes: 
      - name: zhongtai-pg-volume
        hostPath:
          path: /data/pg